export interface Theme {
  id: string
  name: string
  tokens: Record<string, string>
}

export const THEMES: Theme[] = [
  {
    id: 'neon-editorial',
    name: 'Neon Editorial',
    tokens: {
      '--color-base': '#0a0a0f',
      '--color-base-2': '#0d0d1a',
      '--color-paper': '#f7f5ff',
      '--color-ink': '#0a0a0f',
      '--color-blue': '#2879ff',
      '--color-blue-glow': '#2879ff44',
      '--color-violet': '#9b5cff',
      '--color-violet-glow': '#9b5cff44',
      '--color-pink': '#ff3ca6',
      '--color-pink-glow': '#ff3ca644',
      '--color-lime': '#c8ff3d',
      '--color-lime-glow': '#c8ff3d44',
      '--color-orange': '#ff7a2f',
      '--color-text': '#f7f5ff',
      '--color-text-muted': '#a8a3bd',
      '--color-text-dim': '#6b6780',
      '--color-border': '#ffffff18',
      '--color-tile-dark': '#172247',
      '--color-accent-1': '#2879ff',
      '--color-accent-2': '#9b5cff',
      '--color-accent-3': '#ff3ca6',
      '--color-accent-4': '#c8ff3d',
      '--color-accent-5': '#ff7a2f',
    },
  },
  {
    id: 'acid-mono',
    name: 'Acid Mono',
    tokens: {
      '--color-base': '#080809',
      '--color-base-2': '#0d0d10',
      '--color-paper': '#eef6f0',
      '--color-ink': '#080809',
      '--color-blue': '#22d3ee',
      '--color-blue-glow': '#22d3ee33',
      '--color-violet': '#22d3ee',
      '--color-violet-glow': '#22d3ee26',
      '--color-pink': '#c9ff3d',
      '--color-pink-glow': '#c9ff3d2e',
      '--color-lime': '#c9ff3d',
      '--color-lime-glow': '#c9ff3d33',
      '--color-orange': '#c9ff3d',
      '--color-text': '#eef6f0',
      '--color-text-muted': '#a7b3ac',
      '--color-text-dim': '#5c665f',
      '--color-border': '#eef6f018',
      '--color-tile-dark': '#101418',
      '--color-accent-1': '#22d3ee',
      '--color-accent-2': '#22d3ee',
      '--color-accent-3': '#c9ff3d',
      '--color-accent-4': '#c9ff3d',
      '--color-accent-5': '#c9ff3d',
    },
  },
  {
    id: 'jewel-luxe',
    name: 'Jewel Luxe',
    tokens: {
      '--color-base': '#0c0908',
      '--color-base-2': '#14100d',
      '--color-paper': '#f6efe2',
      '--color-ink': '#0c0908',
      '--color-blue': '#7b2d8b',
      '--color-blue-glow': '#7b2d8b44',
      '--color-violet': '#9d4edd',
      '--color-violet-glow': '#9d4edd44',
      '--color-pink': '#d4af37',
      '--color-pink-glow': '#d4af3744',
      '--color-lime': '#2a9d8f',
      '--color-lime-glow': '#2a9d8f44',
      '--color-orange': '#c1121f',
      '--color-text': '#f6efe2',
      '--color-text-muted': '#cfc1a8',
      '--color-text-dim': '#8a7f6b',
      '--color-border': '#f6efe220',
      '--color-tile-dark': '#241a10',
      '--color-accent-1': '#9d4edd',
      '--color-accent-2': '#d4af37',
      '--color-accent-3': '#c1121f',
      '--color-accent-4': '#2a9d8f',
      '--color-accent-5': '#7b2d8b',
    },
  },
  {
    id: 'solar-ember',
    name: 'Solar Ember',
    tokens: {
      '--color-base': '#0d0a08',
      '--color-base-2': '#15110d',
      '--color-paper': '#fdeee0',
      '--color-ink': '#0d0a08',
      '--color-blue': '#ffb74d',
      '--color-blue-glow': '#ffb74d3a',
      '--color-violet': '#ff7a2f',
      '--color-violet-glow': '#ff7a2f3a',
      '--color-pink': '#ff5e5b',
      '--color-pink-glow': '#ff5e5b3a',
      '--color-lime': '#ffd54f',
      '--color-lime-glow': '#ffd54f3a',
      '--color-orange': '#ff9e64',
      '--color-text': '#fdeee0',
      '--color-text-muted': '#d2bfa9',
      '--color-text-dim': '#8a7660',
      '--color-border': '#fdeee01c',
      '--color-tile-dark': '#1c150e',
      '--color-accent-1': '#ffb74d',
      '--color-accent-2': '#ff7a2f',
      '--color-accent-3': '#ff5e5b',
      '--color-accent-4': '#ffd54f',
      '--color-accent-5': '#ff9e64',
    },
  },
  {
    id: 'paper-earth',
    name: 'Paper Earth',
    tokens: {
      '--color-base': '#f3ede2',
      '--color-base-2': '#ece4d4',
      '--color-paper': '#211d18',
      '--color-ink': '#f3ede2',
      '--color-blue': '#2a9d8f',
      '--color-blue-glow': '#2a9d8f33',
      '--color-violet': '#9b5cff',
      '--color-violet-glow': '#9b5cff26',
      '--color-pink': '#e07a5f',
      '--color-pink-glow': '#e07a5f33',
      '--color-lime': '#e9c46a',
      '--color-lime-glow': '#e9c46a40',
      '--color-orange': '#e76f51',
      '--color-text': '#211d18',
      '--color-text-muted': '#5c564b',
      '--color-text-dim': '#8a8375',
      '--color-border': '#211d1822',
      '--color-tile-dark': '#2b2a26',
      '--color-accent-1': '#2a9d8f',
      '--color-accent-2': '#9b5cff',
      '--color-accent-3': '#e07a5f',
      '--color-accent-4': '#e9c46a',
      '--color-accent-5': '#e76f51',
    },
  },
]

export const DEFAULT_THEME = 'neon-editorial'
export const THEME_STORAGE_KEY = 'portfolio-theme'

export function getThemeTokens(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0]
}
