export interface Theme {
  id: string
  name: string
  tokens: Record<string, string>
}

export const THEMES: Theme[] = [
  {
    id: 'neon-editorial',
    name: 'Neon Editorial',
    tokens: {
      '--color-base': '#0a0a0f',
      '--color-base-2': '#0d0d1a',
      '--color-paper': '#f7f5ff',
      '--color-ink': '#0a0a0f',
      '--color-blue': '#2879ff',
      '--color-blue-glow': '#2879ff44',
      '--color-violet': '#9b5cff',
      '--color-violet-glow': '#9b5cff44',
      '--color-pink': '#ff3ca6',
      '--color-pink-glow': '#ff3ca644',
      '--color-lime': '#c8ff3d',
      '--color-lime-glow': '#c8ff3d44',
      '--color-orange': '#ff7a2f',
      '--color-text': '#f7f5ff',
      '--color-text-muted': '#a8a3bd',
      '--color-text-dim': '#6b6780',
      '--color-border': '#ffffff18',
      '--color-tile-dark': '#172247',
      '--color-accent-1': '#2879ff',
      '--color-accent-2': '#9b5cff',
      '--color-accent-3': '#ff3ca6',
      '--color-accent-4': '#c8ff3d',
      '--color-accent-5': '#ff7a2f',
    },
  },
  {
    id: 'acid-mono',
    name: 'Acid Mono',
    tokens: {
      '--color-base': '#080809',
      '--color-base-2': '#0d0d10',
      '--color-paper': '#eef6f0',
      '--color-ink': '#080809',
      '--color-blue': '#22d3ee',
      '--color-blue-glow': '#22d3ee33',
      '--color-violet': '#22d3ee',
      '--color-violet-glow': '#22d3ee26',
      '--color-pink': '#c9ff3d',
      '--color-pink-glow': '#c9ff3d2e',
      '--color-lime': '#c9ff3d',
      '--color-lime-glow': '#c9ff3d33',
      '--color-orange': '#c9ff3d',
      '--color-text': '#eef6f0',
      '--color-text-muted': '#a7b3ac',
      '--color-text-dim': '#5c665f',
      '--color-border': '#eef6f018',
      '--color-tile-dark': '#101418',
      '--color-accent-1': '#22d3ee',
      '--color-accent-2': '#22d3ee',
      '--color-accent-3': '#c9ff3d',
      '--color-accent-4': '#c9ff3d',
      '--color-accent-5': '#c9ff3d',
    },
  },
  {
    id: 'jewel-luxe',
    name: 'Jewel Luxe',
    tokens: {
      '--color-base': '#0c0908',
      '--color-base-2': '#14100d',
      '--color-paper': '#f6efe2',
      '--color-ink': '#0c0908',
      '--color-blue': '#7b2d8b',
      '--color-blue-glow': '#7b2d8b44',
      '--color-violet': '#9d4edd',
      '--color-violet-glow': '#9d4edd44',
      '--color-pink': '#d4af37',
      '--color-pink-glow': '#d4af3744',
      '--color-lime': '#2a9d8f',
      '--color-lime-glow': '#2a9d8f44',
      '--color-orange': '#c1121f',
      '--color-text': '#f6efe2',
      '--color-text-muted': '#cfc1a8',
      '--color-text-dim': '#8a7f6b',
      '--color-border': '#f6efe220',
      '--color-tile-dark': '#241a10',
      '--color-accent-1': '#9d4edd',
      '--color-accent-2': '#d4af37',
      '--color-accent-3': '#c1121f',
      '--color-accent-4': '#2a9d8f',
      '--color-accent-5': '#7b2d8b',
    },
  },
  {
    id: 'solar-ember',
    name: 'Solar Ember',
    tokens: {
      '--color-base': '#0d0a08',
      '--color-base-2': '#15110d',
      '--color-paper': '#fdeee0',
      '--color-ink': '#0d0a08',
      '--color-blue': '#ffb74d',
      '--color-blue-glow': '#ffb74d3a',
      '--color-violet': '#ff7a2f',
      '--color-violet-glow': '#ff7a2f3a',
      '--color-pink': '#ff5e5b',
      '--color-pink-glow': '#ff5e5b3a',
      '--color-lime': '#ffd54f',
      '--color-lime-glow': '#ffd54f3a',
      '--color-orange': '#ff9e64',
      '--color-text': '#fdeee0',
      '--color-text-muted': '#d2bfa9',
      '--color-text-dim': '#8a7660',
      '--color-border': '#fdeee01c',
      '--color-tile-dark': '#1c150e',
      '--color-accent-1': '#ffb74d',
      '--color-accent-2': '#ff7a2f',
      '--color-accent-3': '#ff5e5b',
      '--color-accent-4': '#ffd54f',
      '--color-accent-5': '#ff9e64',
    },
  },
  {
    id: 'arcade-pop',
    name: 'Arcade Pop',
    tokens: {
      '--color-base': '#0a0e14',
      '--color-base-2': '#0e1622',
      '--color-paper': '#eef6fb',
      '--color-ink': '#0a0e14',
      '--color-blue': '#00a6ff',
      '--color-blue-glow': '#00a6ff44',
      '--color-violet': '#1fb8ff',
      '--color-violet-glow': '#1fb8ff3a',
      '--color-pink': '#ff3b4e',
      '--color-pink-glow': '#ff3b4e3a',
      '--color-lime': '#ffc145',
      '--color-lime-glow': '#ffc1453a',
      '--color-orange': '#ff8a3d',
      '--color-text': '#eef6fb',
      '--color-text-muted': '#a9bdcc',
      '--color-text-dim': '#5a6a7a',
      '--color-border': '#eef6fb1c',
      '--color-tile-dark': '#101d2c',
      '--color-accent-1': '#00a6ff',
      '--color-accent-2': '#ff3b4e',
      '--color-accent-3': '#ffc145',
      '--color-accent-4': '#3ee6a0',
      '--color-accent-5': '#ff8a3d',
    },
  },
  {
    id: 'firebrand',
    name: 'Firebrand',
    tokens: {
      '--color-base': '#160f0a',
      '--color-base-2': '#1f1510',
      '--color-paper': '#fbf1e3',
      '--color-ink': '#160f0a',
      '--color-blue': '#ff9e2c',
      '--color-blue-glow': '#ff9e2c3a',
      '--color-violet': '#ff4d3d',
      '--color-violet-glow': '#ff4d3d3a',
      '--color-pink': '#ffd23f',
      '--color-pink-glow': '#ffd23f3a',
      '--color-lime': '#d7e250',
      '--color-lime-glow': '#d7e2503a',
      '--color-orange': '#e85b2a',
      '--color-text': '#fbf1e3',
      '--color-text-muted': '#d2bfa6',
      '--color-text-dim': '#8a7a66',
      '--color-border': '#fbf1e31c',
      '--color-tile-dark': '#2a201a',
      '--color-accent-1': '#ff4d3d',
      '--color-accent-2': '#ff9e2c',
      '--color-accent-3': '#ffd23f',
      '--color-accent-4': '#d7e250',
      '--color-accent-5': '#e85b2a',
    },
  },
  {
    id: 'paper-earth',
    name: 'Paper Earth',
    tokens: {
      '--color-base': '#f3ede2',
      '--color-base-2': '#ece4d4',
      '--color-paper': '#211d18',
      '--color-ink': '#f3ede2',
      '--color-blue': '#2a9d8f',
      '--color-blue-glow': '#2a9d8f33',
      '--color-violet': '#9b5cff',
      '--color-violet-glow': '#9b5cff26',
      '--color-pink': '#e07a5f',
      '--color-pink-glow': '#e07a5f33',
      '--color-lime': '#e9c46a',
      '--color-lime-glow': '#e9c46a40',
      '--color-orange': '#e76f51',
      '--color-text': '#211d18',
      '--color-text-muted': '#5c564b',
      '--color-text-dim': '#8a8375',
      '--color-border': '#211d1822',
      '--color-tile-dark': '#2b2a26',
      '--color-accent-1': '#2a9d8f',
      '--color-accent-2': '#9b5cff',
      '--color-accent-3': '#e07a5f',
      '--color-accent-4': '#e9c46a',
      '--color-accent-5': '#e76f51',
    },
  },
  {
    id: 'pastel-pop',
    name: 'Pastel Pop',
    tokens: {
      '--color-base': '#fdf2f1',
      '--color-base-2': '#f9e7e2',
      '--color-paper': '#5a3f45',
      '--color-ink': '#fdf2f1',
      '--color-blue': '#6fb3e0',
      '--color-blue-glow': '#6fb3e044',
      '--color-violet': '#b79ce6',
      '--color-violet-glow': '#b79ce644',
      '--color-pink': '#ff7a9c',
      '--color-pink-glow': '#ff7a9c44',
      '--color-lime': '#8fd14f',
      '--color-lime-glow': '#8fd14f44',
      '--color-orange': '#ffb35c',
      '--color-text': '#5a3f45',
      '--color-text-muted': '#8a6a63',
      '--color-text-dim': '#c4aca4',
      '--color-border': '#5a3f4522',
      '--color-tile-dark': '#f1e3dd',
      '--color-accent-1': '#6fb3e0',
      '--color-accent-2': '#b79ce6',
      '--color-accent-3': '#ff7a9c',
      '--color-accent-4': '#8fd14f',
      '--color-accent-5': '#ffb35c',
    },
  },
  {
    id: 'noir',
    name: 'Noir',
    tokens: {
      '--color-base': '#0e0e10',
      '--color-base-2': '#161619',
      '--color-paper': '#ecebe6',
      '--color-ink': '#0e0e10',
      '--color-blue': '#ecebe6',
      '--color-blue-glow': '#ecebe633',
      '--color-violet': '#d9d8d2',
      '--color-violet-glow': '#d9d8d233',
      '--color-pink': '#c9c7c0',
      '--color-pink-glow': '#c9c7c033',
      '--color-lime': '#ecebe6',
      '--color-lime-glow': '#ecebe633',
      '--color-orange': '#b9b6ae',
      '--color-text': '#ecebe6',
      '--color-text-muted': '#a4a29b',
      '--color-text-dim': '#61605b',
      '--color-border': '#ecebe61c',
      '--color-tile-dark': '#1c1c20',
      '--color-accent-1': '#ecebe6',
      '--color-accent-2': '#d9d8d2',
      '--color-accent-3': '#b9b6ae',
      '--color-accent-4': '#8e8c85',
      '--color-accent-5': '#6e6c66',
    },
  },
  {
    id: 'forest-floor',
    name: 'Forest Floor',
    tokens: {
      '--color-base': '#0f1512',
      '--color-base-2': '#151d18',
      '--color-paper': '#f2ead9',
      '--color-ink': '#0f1512',
      '--color-blue': '#d4a24a',
      '--color-blue-glow': '#d4a24a3a',
      '--color-violet': '#8fae57',
      '--color-violet-glow': '#8fae573a',
      '--color-pink': '#c96f4a',
      '--color-pink-glow': '#c96f4a3a',
      '--color-lime': '#a8c686',
      '--color-lime-glow': '#a8c6863a',
      '--color-orange': '#e08a5a',
      '--color-text': '#f2ead9',
      '--color-text-muted': '#a3ab93',
      '--color-text-dim': '#5f6b5c',
      '--color-border': '#f2ead91c',
      '--color-tile-dark': '#1c241d',
      '--color-accent-1': '#6f9350',
      '--color-accent-2': '#cf9c43',
      '--color-accent-3': '#c4663d',
      '--color-accent-4': '#a8c686',
      '--color-accent-5': '#8a6b3f',
    },
  },
]

export const DEFAULT_THEME = 'neon-editorial'
export const THEME_STORAGE_KEY = 'portfolio-theme'

export function getThemeTokens(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0]
}
